name: Innofantit
favicon: null
layout_spectrum: 0.55202
typography_spectrum: 1
title: Tahto Tehdä Toisin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff00c3'
    - '#b15832'
    - '#bb5533'
    - '#ff00d1'
    - '#b3552f'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
