name: Innofantit
favicon: null
layout_spectrum: 0.48282862664200366
typography_spectrum: 0.27346095838584006
title: Tahto Tehdä Toisiin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  brandStrength: 0.48607416939921677
  lightness: 0.8943569341208786
  saturation: 0.23076816368848085
  rhythmicContrast: 0.8248279474209994
purpose: []
