name: Innofantit
favicon: null
layout_spectrum: 0.97993
typography_spectrum: 1
title: Tahto Tehdä Toisin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#72111f'
    - '#b15832'
    - '#660000'
    - '#aa5500'
    - '#800000'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
